## Settings

In [1]:
## auto reload modules
%reload_ext autoreload
%autoreload 2

## Dependencies

In [2]:
## libraries
import sys
import pickle
import logging
from pathlib import Path
from IPython.display import Markdown, display

## path
root = Path.cwd().resolve().parent
sys.path.insert(0, str(root))

## modules
from src.data.builders import (
    load_processed_data, 
    load_falsified_data
)
from src.estimators.factories import load_estimators
from src.evaluators.caching import load_notebook_cache
from src.evaluators.tables import main_table
from src.evaluators.falsifying import (
    train_falsified_transfer,
    train_falsified_agreement,
    train_falsified_consensus,
    compile_falsified_transfer,
    compile_falsified_agreement,
    compile_falsified_consensus,
    compile_falsified_full,
    stat_falsified_test,
    stat_falsified_summary
)

## constants
from src.evaluators.config import (
    FRONTIER_METRICS,
    CONSENSUS_METRICS
)
from src.evaluators.config import (
    FEAT_X, 
    FEAT_Z, 
    TARGET
)

## Initialization

In [3]:
## reproducibility
N_DECIMALS = 2
N_REPEATS = 30
RANDOM_STATE = 42
FORCE_RECOMPUTE = False

## load data and models
_disable = logging.root.manager.disable
logging.disable(logging.INFO)
try:
    data_proc = load_processed_data()
    data_fals = load_falsified_data()
finally:
    logging.disable(_disable)
    models = load_estimators(random_state = RANDOM_STATE)

## view data shape
n_obs, n_feat = data_proc.shape
print(f"Original Data: {n_feat} features, {n_obs} observations")
print("Falsified Data:")
for method, data in data_fals.items():
    n_r, n_c = data.shape
    print(f" - {method}: {n_c} features, {n_r} observations")

## view model surface
n_mods = len(models)
print(f"Learned Models: {n_mods} estimators")

## cache setup
cache_path = root / "notebooks" / "cache" / "falsify_results.pkl"
cache_metadata = {
    "n_obs": len(data_proc),
    "n_repeats": N_REPEATS,
    "random_state": RANDOM_STATE,
    "model_names": sorted(models.keys()),
    "target": TARGET,
    "feat_x": list(FEAT_X),
    "feat_z": list(FEAT_Z),
}
cache_keys = (
    "results_falsified_transfer",
    "results_falsified_agreement",
    "results_falsified_consensus",
)
cache_payload = load_notebook_cache(
    cache_path = cache_path,
    metadata = cache_metadata,
    required_keys = cache_keys,
    force_recompute = FORCE_RECOMPUTE,
)
if cache_payload is not None:
    globals().update({key: cache_payload[key] for key in cache_keys})

Original Data: 32 features, 25 observations
Falsified Data:
 - random_generate: 32 features, 25 observations
 - target_remap: 32 features, 25 observations
 - vector_generate: 32 features, 25 observations
Learned Models: 9 estimators
Forced recomputation for /Users/nickkunz/Documents/Nick’s MacBook Pro/Python/network-capacity/notebooks/cache/falsify_results.pkl

## Training

In [4]:
## train falsified transfer
if cache_payload is None:
    results_dict_falsified_transfer = train_falsified_transfer(
        data_proc = data_proc,
        data_fals = data_fals,
        models = models,
        feat_x = FEAT_X,
        feat_z = FEAT_Z,
        target = TARGET,
        group = "domain",
        n_repeats = N_REPEATS,
        random_state = RANDOM_STATE
    )

transfer: original:   0%|          | 0/270 [00:00<?, ?job/s]

transfer: original:   0%|          | 1/270 [00:05<22:47,  5.08s/job]

transfer: original:   1%|          | 3/270 [00:05<06:04,  1.36s/job]

transfer: original:   3%|▎         | 9/270 [00:05<01:34,  2.78job/s]

transfer: original:  17%|█▋        | 45/270 [00:05<00:11, 19.72job/s]

transfer: original:  23%|██▎       | 61/270 [00:05<00:07, 28.45job/s]

transfer: original:  28%|██▊       | 75/270 [00:05<00:05, 37.36job/s]

transfer: original:  33%|███▎      | 89/270 [00:05<00:03, 46.63job/s]

transfer: original:  38%|███▊      | 102/270 [00:07<00:07, 21.54job/s]

transfer: original:  41%|████      | 111/270 [00:08<00:10, 15.39job/s]

transfer: original:  46%|████▌     | 123/270 [00:09<00:08, 16.96job/s]

transfer: original:  48%|████▊     | 129/270 [00:09<00:07, 17.89job/s]

transfer: original:  51%|█████▏    | 139/270 [00:09<00:07, 16.86job/s]

transfer: original:  53%|█████▎    | 143/270 [00:10<00:07, 16.61job/s]

transfer: original:  63%|██████▎   | 171/270 [00:10<00:02, 37.10job/s]

transfer: original:  67%|██████▋   | 181/270 [00:19<00:20,  4.31job/s]

transfer: original:  70%|███████   | 189/270 [00:19<00:15,  5.35job/s]

transfer: original:  73%|███████▎  | 196/270 [00:19<00:11,  6.51job/s]

transfer: original:  75%|███████▍  | 202/270 [00:26<00:23,  2.86job/s]

transfer: original:  79%|███████▊  | 212/270 [00:26<00:13,  4.18job/s]

transfer: original:  81%|████████  | 218/270 [00:31<00:19,  2.67job/s]

transfer: original:  82%|████████▏ | 222/270 [00:31<00:15,  3.14job/s]

transfer: original:  84%|████████▎ | 226/270 [00:32<00:11,  3.70job/s]

transfer: original:  85%|████████▍ | 229/270 [00:36<00:18,  2.17job/s]

transfer: original:  86%|████████▌ | 231/270 [00:37<00:17,  2.20job/s]

transfer: original:  87%|████████▋ | 236/270 [00:37<00:10,  3.18job/s]

transfer: original:  89%|████████▉ | 241/270 [00:37<00:07,  4.11job/s]

transfer: original:  91%|█████████ | 245/270 [00:40<00:09,  2.66job/s]

transfer: original:  91%|█████████▏| 247/270 [00:41<00:08,  2.69job/s]

transfer: original:  92%|█████████▏| 249/270 [00:41<00:06,  3.03job/s]

transfer: original:  93%|█████████▎| 251/270 [00:42<00:05,  3.53job/s]

transfer: original:  95%|█████████▍| 256/270 [00:42<00:02,  5.76job/s]

transfer: original:  96%|█████████▌| 258/270 [00:42<00:02,  5.77job/s]

transfer: original:  96%|█████████▋| 260/270 [00:42<00:01,  6.66job/s]

transfer: original:  97%|█████████▋| 262/270 [00:44<00:02,  2.79job/s]

transfer: original:  98%|█████████▊| 264/270 [00:44<00:01,  3.55job/s]

transfer: original:  99%|█████████▊| 266/270 [00:45<00:00,  4.27job/s]

transfer: original: 100%|█████████▉| 269/270 [00:45<00:00,  6.15job/s]

transfer: original: 100%|██████████| 270/270 [00:45<00:00,  5.98job/s]

transfer: frozen:   0%|          | 0/810 [00:00<?, ?job/s]

transfer: frozen:   1%|▏         | 11/810 [00:00<00:08, 94.37job/s]

transfer: frozen:   4%|▍         | 33/810 [00:00<00:06, 123.05job/s]

transfer: frozen:   8%|▊         | 65/810 [00:00<00:04, 163.85job/s]

transfer: frozen:  11%|█         | 91/810 [00:01<00:16, 44.41job/s]

transfer: frozen:  13%|█▎        | 102/810 [00:03<00:33, 21.15job/s]

transfer: frozen:  13%|█▎        | 102/810 [00:14<00:33, 21.15job/s]

transfer: frozen:  22%|██▏       | 181/810 [00:18<01:31,  6.84job/s]

transfer: frozen:  23%|██▎       | 189/810 [00:19<01:25,  7.25job/s]

transfer: frozen:  25%|██▌       | 205/810 [00:19<01:08,  8.88job/s]

transfer: frozen:  30%|██▉       | 241/810 [00:20<00:45, 12.49job/s]

transfer: frozen:  30%|██▉       | 241/810 [00:34<00:45, 12.49job/s]

transfer: frozen:  30%|███       | 245/810 [00:35<02:47,  3.38job/s]

transfer: frozen:  33%|███▎      | 265/810 [00:35<01:58,  4.59job/s]

transfer: frozen:  58%|█████▊    | 471/810 [00:36<00:14, 23.37job/s]

transfer: frozen:  60%|██████    | 487/810 [00:40<00:19, 16.71job/s]

transfer: frozen:  61%|██████▏   | 498/810 [00:42<00:22, 13.89job/s]

transfer: frozen:  62%|██████▏   | 506/810 [00:44<00:24, 12.40job/s]

transfer: frozen:  63%|██████▎   | 512/810 [00:46<00:29, 10.23job/s]

transfer: frozen:  64%|██████▎   | 516/810 [00:47<00:31,  9.39job/s]

transfer: frozen:  64%|██████▍   | 519/810 [00:48<00:35,  8.15job/s]

transfer: frozen:  64%|██████▍   | 522/810 [00:48<00:35,  8.04job/s]

transfer: frozen:  65%|██████▍   | 526/810 [00:48<00:32,  8.72job/s]

transfer: frozen:  65%|██████▌   | 528/810 [00:50<00:47,  5.90job/s]

transfer: frozen:  65%|██████▌   | 530/810 [00:51<00:51,  5.40job/s]

transfer: frozen:  66%|██████▌   | 531/810 [00:51<00:52,  5.35job/s]

transfer: frozen:  66%|██████▌   | 532/810 [00:51<00:55,  5.02job/s]

transfer: frozen:  66%|██████▌   | 533/810 [00:51<01:02,  4.44job/s]

transfer: frozen:  66%|██████▌   | 534/810 [00:52<01:02,  4.39job/s]

transfer: frozen:  66%|██████▌   | 535/810 [00:53<01:33,  2.93job/s]

transfer: frozen:  80%|████████  | 650/810 [00:53<00:02, 79.83job/s]

transfer: frozen:  84%|████████▍ | 679/810 [00:54<00:02, 54.57job/s]

transfer: frozen:  86%|████████▋ | 700/810 [00:54<00:01, 56.14job/s]

transfer: frozen:  89%|████████▉ | 721/810 [00:58<00:05, 17.72job/s]

transfer: frozen:  90%|█████████ | 733/810 [00:58<00:04, 19.16job/s]

transfer: frozen:  92%|█████████▏| 743/810 [01:02<00:07,  9.32job/s]

transfer: frozen:  93%|█████████▎| 753/810 [01:06<00:08,  6.65job/s]

transfer: frozen:  94%|█████████▎| 758/810 [01:06<00:07,  7.16job/s]

transfer: frozen:  94%|█████████▍| 762/810 [01:06<00:06,  7.85job/s]

transfer: frozen:  95%|█████████▍| 766/810 [01:06<00:05,  8.74job/s]

transfer: frozen:  95%|█████████▌| 770/810 [01:09<00:09,  4.37job/s]

transfer: frozen:  95%|█████████▌| 773/810 [01:10<00:07,  4.83job/s]

transfer: frozen:  96%|█████████▌| 777/810 [01:10<00:05,  5.60job/s]

transfer: frozen:  96%|█████████▋| 781/810 [01:10<00:04,  6.35job/s]

transfer: frozen:  97%|█████████▋| 785/810 [01:13<00:07,  3.23job/s]

transfer: frozen:  97%|█████████▋| 787/810 [01:14<00:07,  3.28job/s]

transfer: frozen:  98%|█████████▊| 793/810 [01:14<00:03,  4.88job/s]

transfer: frozen:  98%|█████████▊| 797/810 [01:14<00:02,  6.15job/s]

transfer: frozen:  99%|█████████▊| 799/810 [01:15<00:01,  6.73job/s]

transfer: frozen:  99%|█████████▉| 801/810 [01:17<00:03,  2.96job/s]

transfer: frozen:  99%|█████████▉| 803/810 [01:17<00:02,  3.26job/s]

transfer: frozen:  99%|█████████▉| 805/810 [01:17<00:01,  4.01job/s]

transfer: frozen: 100%|█████████▉| 809/810 [01:18<00:00,  6.15job/s]

transfer: frozen: 100%|██████████| 810/810 [01:18<00:00, 10.37job/s]

transfer: retrain:   0%|          | 0/810 [00:00<?, ?job/s]

transfer: retrain:   1%|          | 6/810 [00:00<00:13, 57.83job/s]

transfer: retrain:   4%|▍         | 33/810 [00:00<00:04, 157.90job/s]

transfer: retrain:   6%|▌         | 49/810 [00:00<00:05, 130.94job/s]

transfer: retrain:  10%|▉         | 77/810 [00:00<00:04, 178.37job/s]

transfer: retrain:  12%|█▏        | 96/810 [00:01<00:19, 36.08job/s]

transfer: retrain:  13%|█▎        | 109/810 [00:03<00:34, 20.19job/s]

transfer: retrain:  13%|█▎        | 109/810 [00:16<00:34, 20.19job/s]

transfer: retrain:  22%|██▏       | 181/810 [00:19<01:44,  6.03job/s]

transfer: retrain:  24%|██▍       | 193/810 [00:19<01:30,  6.80job/s]

transfer: retrain:  25%|██▍       | 200/810 [00:20<01:21,  7.48job/s]

transfer: retrain:  26%|██▌       | 207/810 [00:20<01:13,  8.21job/s]

transfer: retrain:  29%|██▉       | 233/810 [00:20<00:47, 12.09job/s]

transfer: retrain:  30%|███       | 245/810 [00:35<03:04,  3.07job/s]

transfer: retrain:  32%|███▏      | 257/810 [00:36<02:20,  3.94job/s]

transfer: retrain:  33%|███▎      | 265/810 [00:36<02:02,  4.45job/s]

transfer: retrain:  58%|█████▊    | 471/810 [00:36<00:10, 33.00job/s]

transfer: retrain:  63%|██████▎   | 507/810 [00:45<00:19, 15.43job/s]

transfer: retrain:  66%|██████▌   | 532/810 [00:52<00:28,  9.87job/s]

transfer: retrain:  68%|██████▊   | 550/810 [00:53<00:24, 10.43job/s]

transfer: retrain:  80%|████████  | 648/810 [00:53<00:07, 21.00job/s]

transfer: retrain:  84%|████████▍ | 682/810 [00:54<00:05, 22.81job/s]

transfer: retrain:  87%|████████▋ | 707/810 [00:55<00:04, 25.34job/s]

transfer: retrain:  90%|████████▉ | 726/810 [00:59<00:05, 14.70job/s]

transfer: retrain:  91%|█████████▏| 740/810 [01:03<00:06, 10.13job/s]

transfer: retrain:  93%|█████████▎| 753/810 [01:07<00:07,  7.93job/s]

transfer: retrain:  94%|█████████▍| 760/810 [01:07<00:05,  8.41job/s]

transfer: retrain:  95%|█████████▍| 766/810 [01:07<00:04,  9.08job/s]

transfer: retrain:  95%|█████████▌| 771/810 [01:11<00:07,  5.51job/s]

transfer: retrain:  96%|█████████▌| 775/810 [01:11<00:05,  5.91job/s]

transfer: retrain:  96%|█████████▌| 778/810 [01:11<00:05,  6.40job/s]

transfer: retrain:  96%|█████████▋| 781/810 [01:11<00:04,  6.80job/s]

transfer: retrain:  97%|█████████▋| 783/810 [01:12<00:03,  6.91job/s]

transfer: retrain:  97%|█████████▋| 785/810 [01:14<00:08,  3.07job/s]

transfer: retrain:  97%|█████████▋| 787/810 [01:15<00:06,  3.33job/s]

transfer: retrain:  98%|█████████▊| 790/810 [01:15<00:04,  4.26job/s]

transfer: retrain:  98%|█████████▊| 792/810 [01:15<00:03,  4.87job/s]

transfer: retrain:  98%|█████████▊| 795/810 [01:15<00:02,  6.33job/s]

transfer: retrain:  99%|█████████▊| 798/810 [01:16<00:01,  7.46job/s]

transfer: retrain:  99%|█████████▉| 800/810 [01:16<00:01,  7.63job/s]

transfer: retrain:  99%|█████████▉| 802/810 [01:18<00:02,  2.92job/s]

transfer: retrain:  99%|█████████▉| 804/810 [01:18<00:01,  3.56job/s]

transfer: retrain: 100%|█████████▉| 806/810 [01:18<00:00,  4.32job/s]

transfer: retrain: 100%|██████████| 810/810 [01:18<00:00, 10.28job/s]

In [5]:
## train falsified prediction consensus
if cache_payload is None:
    results_dict_falsified_agreement = train_falsified_agreement(
        data_proc = data_proc,
        data_fals = data_fals,
        models = models,
        feat_x = FEAT_X,
        feat_z = FEAT_Z,
        target = TARGET,
        n_repeats = N_REPEATS,
        random_state = RANDOM_STATE,
    )

agreement: original:   0%|          | 0/270 [00:00<?, ?job/s]

agreement: original:   1%|          | 3/270 [00:00<00:09, 28.70job/s]

agreement: original:  13%|█▎        | 35/270 [00:00<00:01, 156.21job/s]

agreement: original:  19%|█▊        | 50/270 [00:00<00:01, 135.73job/s]

agreement: original:  27%|██▋       | 73/270 [00:00<00:01, 151.76job/s]

agreement: original:  34%|███▎      | 91/270 [00:01<00:05, 35.02job/s]

agreement: original:  37%|███▋      | 101/270 [00:03<00:08, 19.11job/s]

agreement: original:  37%|███▋      | 101/270 [00:17<00:08, 19.11job/s]

agreement: original:  67%|██████▋   | 181/270 [00:18<00:13,  6.64job/s]

agreement: original:  70%|███████   | 189/270 [00:18<00:11,  7.09job/s]

agreement: original:  90%|█████████ | 244/270 [00:19<00:02, 12.91job/s]

agreement: original:  94%|█████████▎| 253/270 [00:22<00:01,  9.10job/s]

agreement: original:  96%|█████████▋| 260/270 [00:23<00:01,  9.70job/s]

agreement: original:  98%|█████████▊| 265/270 [00:25<00:00,  7.12job/s]

agreement: original: 100%|█████████▉| 269/270 [00:25<00:00,  7.72job/s]

agreement: original: 100%|██████████| 270/270 [00:25<00:00, 10.45job/s]

agreement: frozen:   0%|          | 0/810 [00:00<?, ?job/s]

agreement: frozen:   2%|▏         | 13/810 [00:00<00:09, 84.59job/s]

agreement: frozen:   4%|▍         | 33/810 [00:00<00:06, 122.70job/s]

agreement: frozen:   7%|▋         | 53/810 [00:00<00:05, 127.69job/s]

agreement: frozen:  11%|█         | 91/810 [00:01<00:17, 40.98job/s]

agreement: frozen:  12%|█▏        | 100/810 [00:03<00:33, 21.37job/s]

agreement: frozen:  22%|██▏       | 181/810 [00:18<01:30,  6.96job/s]

agreement: frozen:  23%|██▎       | 185/810 [00:19<01:30,  6.89job/s]

agreement: frozen:  24%|██▍       | 193/810 [00:19<01:20,  7.66job/s]

agreement: frozen:  24%|██▍       | 198/810 [00:19<01:17,  7.93job/s]

agreement: frozen:  30%|██▉       | 241/810 [00:20<00:39, 14.32job/s]

agreement: frozen:  30%|██▉       | 241/810 [00:32<00:39, 14.32job/s]

agreement: frozen:  30%|███       | 245/810 [00:35<02:56,  3.20job/s]

agreement: frozen:  31%|███       | 253/810 [00:35<02:27,  3.77job/s]

agreement: frozen:  32%|███▏      | 258/810 [00:36<02:14,  4.11job/s]

agreement: frozen:  32%|███▏      | 262/810 [00:36<02:00,  4.54job/s]

agreement: frozen:  58%|█████▊    | 470/810 [00:37<00:08, 42.08job/s]

agreement: frozen:  60%|█████▉    | 485/810 [00:40<00:13, 24.04job/s]

agreement: frozen:  61%|██████    | 496/810 [00:43<00:18, 16.78job/s]

agreement: frozen:  62%|██████▏   | 504/810 [00:45<00:23, 12.75job/s]

agreement: frozen:  63%|██████▎   | 510/810 [00:46<00:22, 13.31job/s]

agreement: frozen:  64%|██████▎   | 515/810 [00:48<00:33,  8.75job/s]

agreement: frozen:  64%|██████▍   | 519/810 [00:49<00:35,  8.15job/s]

agreement: frozen:  64%|██████▍   | 522/810 [00:50<00:38,  7.49job/s]

agreement: frozen:  65%|██████▌   | 527/810 [00:50<00:35,  8.00job/s]

agreement: frozen:  65%|██████▌   | 529/810 [00:52<00:48,  5.79job/s]

agreement: frozen:  66%|██████▌   | 531/810 [00:53<00:59,  4.69job/s]

agreement: frozen:  66%|██████▌   | 534/810 [00:53<00:56,  4.92job/s]

agreement: frozen:  66%|██████▌   | 535/810 [00:54<00:59,  4.63job/s]

agreement: frozen:  66%|██████▌   | 536/810 [00:54<01:02,  4.35job/s]

agreement: frozen:  66%|██████▋   | 538/810 [00:54<01:00,  4.48job/s]

agreement: frozen:  81%|████████  | 657/810 [00:54<00:01, 82.65job/s]

agreement: frozen:  84%|████████▎ | 677/810 [00:55<00:02, 64.66job/s]

agreement: frozen:  85%|████████▌ | 692/810 [00:55<00:01, 60.31job/s]

agreement: frozen:  89%|████████▉ | 721/810 [00:59<00:04, 18.80job/s]

agreement: frozen:  90%|█████████ | 730/810 [01:00<00:04, 18.85job/s]

agreement: frozen:  91%|█████████ | 737/810 [01:03<00:07,  9.20job/s]

agreement: frozen:  92%|█████████▏| 742/810 [01:04<00:06,  9.85job/s]

agreement: frozen:  92%|█████████▏| 748/810 [01:04<00:05, 11.13job/s]

agreement: frozen:  93%|█████████▎| 753/810 [01:07<00:10,  5.43job/s]

agreement: frozen:  93%|█████████▎| 756/810 [01:07<00:09,  5.97job/s]

agreement: frozen:  94%|█████████▍| 760/810 [01:07<00:07,  7.06job/s]

agreement: frozen:  95%|█████████▍| 768/810 [01:08<00:04,  9.54job/s]

agreement: frozen:  95%|█████████▌| 771/810 [01:11<00:10,  3.87job/s]

agreement: frozen:  96%|█████████▌| 774/810 [01:11<00:08,  4.31job/s]

agreement: frozen:  96%|█████████▋| 781/810 [01:12<00:04,  6.19job/s]

agreement: frozen:  97%|█████████▋| 784/810 [01:12<00:03,  6.60job/s]

agreement: frozen:  97%|█████████▋| 786/810 [01:15<00:09,  2.65job/s]

agreement: frozen:  97%|█████████▋| 788/810 [01:15<00:07,  3.12job/s]

agreement: frozen:  98%|█████████▊| 790/810 [01:15<00:05,  3.66job/s]

agreement: frozen:  98%|█████████▊| 794/810 [01:16<00:02,  5.36job/s]

agreement: frozen:  98%|█████████▊| 796/810 [01:16<00:02,  5.92job/s]

agreement: frozen:  99%|█████████▊| 798/810 [01:16<00:01,  6.12job/s]

agreement: frozen:  99%|█████████▉| 801/810 [01:18<00:03,  2.85job/s]

agreement: frozen:  99%|█████████▉| 803/810 [01:18<00:01,  3.51job/s]

agreement: frozen: 100%|█████████▉| 806/810 [01:19<00:00,  4.94job/s]

agreement: frozen: 100%|██████████| 810/810 [01:19<00:00,  7.00job/s]

agreement: frozen: 100%|██████████| 810/810 [01:19<00:00, 10.21job/s]

agreement: retrain:   0%|          | 0/810 [00:00<?, ?job/s]

agreement: retrain:   1%|          | 7/810 [00:00<00:12, 64.41job/s]

agreement: retrain:   4%|▍         | 33/810 [00:00<00:04, 166.00job/s]

agreement: retrain:   8%|▊         | 65/810 [00:00<00:03, 219.81job/s]

agreement: retrain:  11%|█         | 91/810 [00:01<00:16, 44.67job/s]

agreement: retrain:  13%|█▎        | 106/810 [00:03<00:29, 24.03job/s]

agreement: retrain:  22%|██▏       | 181/810 [00:18<01:30,  6.95job/s]

agreement: retrain:  23%|██▎       | 185/810 [00:18<01:28,  7.03job/s]

agreement: retrain:  25%|██▍       | 201/810 [00:18<01:09,  8.76job/s]

agreement: retrain:  30%|██▉       | 241/810 [00:18<00:38, 14.75job/s]

agreement: retrain:  30%|██▉       | 241/810 [00:32<00:38, 14.75job/s]

agreement: retrain:  30%|███       | 245/810 [00:34<02:41,  3.50job/s]

agreement: retrain:  31%|███       | 249/810 [00:34<02:29,  3.76job/s]

agreement: retrain:  32%|███▏      | 258/810 [00:34<02:00,  4.59job/s]

agreement: retrain:  33%|███▎      | 266/810 [00:34<01:37,  5.58job/s]

agreement: retrain:  58%|█████▊    | 471/810 [00:34<00:07, 45.46job/s]

agreement: retrain:  66%|██████▌   | 532/810 [00:50<00:23, 11.86job/s]

agreement: retrain:  66%|██████▌   | 534/810 [00:50<00:23, 11.77job/s]

agreement: retrain:  71%|███████   | 577/810 [00:51<00:15, 14.95job/s]

agreement: retrain:  80%|████████  | 649/810 [00:51<00:06, 24.58job/s]

agreement: retrain:  86%|████████▌ | 693/810 [00:52<00:04, 26.82job/s]

agreement: retrain:  90%|████████▉ | 725/810 [00:56<00:04, 18.05job/s]

agreement: retrain:  92%|█████████▏| 748/810 [01:00<00:04, 12.63job/s]

agreement: retrain:  94%|█████████▍| 764/810 [01:04<00:04,  9.77job/s]

agreement: retrain:  96%|█████████▌| 776/810 [01:08<00:04,  7.68job/s]

agreement: retrain:  97%|█████████▋| 784/810 [01:09<00:03,  7.73job/s]

agreement: retrain:  98%|█████████▊| 790/810 [01:12<00:03,  5.96job/s]

agreement: retrain:  98%|█████████▊| 795/810 [01:12<00:02,  6.48job/s]

agreement: retrain:  99%|█████████▊| 799/810 [01:12<00:01,  6.61job/s]

agreement: retrain:  99%|█████████▉| 802/810 [01:15<00:01,  4.62job/s]

agreement: retrain:  99%|█████████▉| 804/810 [01:15<00:01,  4.98job/s]

agreement: retrain: 100%|█████████▉| 807/810 [01:15<00:00,  5.79job/s]

agreement: retrain: 100%|██████████| 810/810 [01:15<00:00,  6.74job/s]

agreement: retrain: 100%|██████████| 810/810 [01:15<00:00, 10.74job/s]

In [6]:
## train falsified pairwise consensus
if cache_payload is None:
    results_dict_falsified_consensus = train_falsified_consensus(
        data_proc = data_proc,
        data_fals = data_fals,
        models = models,
        feat_x = FEAT_X,
        feat_z = FEAT_Z,
        target = TARGET,
        n_repeats = N_REPEATS,
        random_state = RANDOM_STATE
    )

consensus: original fit:   0%|          | 0/9 [00:00<?, ?job/s]

consensus: original fit:  44%|████▍     | 4/9 [00:02<00:03,  1.49job/s]

consensus: original fit:  78%|███████▊  | 7/9 [00:16<00:05,  2.65s/job]

consensus: original fit: 100%|██████████| 9/9 [00:16<00:00,  1.87s/job]

consensus: original fit: 100%|██████████| 9/9 [00:16<00:00,  1.86s/job]

consensus: retrain:   0%|          | 0/27 [00:00<?, ?job/s]

consensus: retrain:   4%|▎         | 1/27 [00:00<00:03,  7.29job/s]

consensus: retrain:  15%|█▍        | 4/27 [00:03<00:21,  1.09job/s]

consensus: retrain:  26%|██▌       | 7/27 [00:17<00:59,  2.97s/job]

consensus: retrain:  33%|███▎      | 9/27 [00:17<00:36,  2.01s/job]

consensus: retrain:  59%|█████▉    | 16/27 [00:18<00:09,  1.21job/s]

consensus: retrain: 100%|██████████| 27/27 [00:18<00:00,  1.43job/s]

## Post-Processing

In [7]:
if cache_payload is None:
    results_falsified_transfer = compile_falsified_transfer(
        results = results_dict_falsified_transfer,
    )
    results_falsified_agreement = compile_falsified_agreement(
        results = results_dict_falsified_agreement,
    )

if cache_payload is None or "results_falsified_full_agreement" not in cache_payload:
    if cache_payload is not None:
        results_dict_falsified_consensus = train_falsified_consensus(
            data_proc = data_proc,
            data_fals = data_fals,
            models = models,
            feat_x = FEAT_X,
            feat_z = FEAT_Z,
            target = TARGET,
            n_repeats = N_REPEATS,
            random_state = RANDOM_STATE,
            n_jobs = -1,
        )
    results_falsified_consensus = compile_falsified_consensus(
        results = results_dict_falsified_consensus,
    )
    results_falsified_full_agreement = compile_falsified_full(
        results = results_dict_falsified_consensus,
        data_proc = data_proc,
        data_fals = data_fals,
        target = TARGET,
    )
    cache_path.parent.mkdir(parents = True, exist_ok = True)
    cache_payload = {
        **(cache_payload or {}),
        "metadata": cache_metadata,
        "results_falsified_transfer": results_falsified_transfer,
        "results_falsified_agreement": results_falsified_agreement,
        "results_falsified_consensus": results_falsified_consensus,
        "results_falsified_full_agreement": results_falsified_full_agreement,
    }
    cache_path.write_bytes(pickle.dumps(cache_payload))
    print(f"Cached falsification results -> {cache_path}")

Cached falsification results -> /Users/nickkunz/Documents/Nick’s MacBook Pro/Python/network-capacity/notebooks/cache/falsify_results.pkl

## Domain Transfer Difference Test
The transfer falsifiability test probes whether deliberately corrupted data reduce EI transfer performance relative to the original empirical baseline. Three falsification types (target remap, random generate, vector generate) are evaluated under frozen and retrained LOGO-CV (domain) protocols and scored by EI per (model x domain). Each falsification method is tested with a paired one-sided Wilcoxon signed-rank statistic comparing falsified and original EI values, with Δ defined as falsified - original.

- **$H_0$**: Falsified EI does not fall below original EI ($\Delta EI \ge 0$).
- **$H_1$**: Falsified EI falls below original EI ($\Delta EI < 0$).

Rejecting $H_0$ establishes that EI transfer performance is significantly weaker on falsified data than on original data.

### Falsification Protocol
Target remap corrupts the target association, while random and vector generation corrupt the input feature geometry. Under the frozen protocol, models trained on original data are evaluated directly on falsified inputs. Under the retrain protocol, models are refit on falsified data and compared back to the original baseline.

### Empirical Test Specification
Original and falsified EI values are paired on (model $\times$ domain) within each falsification method and protocol. The paired median shift, rank-biserial effect size, and Holm-adjusted one-sided p-value summarize whether each destructive intervention produces a consistent EI loss.

In [8]:
## wilcoxon signed-rank test for falsified transfer
results_table_transfer = stat_falsified_test(
    results = results_falsified_transfer,
    feat_value = ["ei"],
    feat_pairs = ["model", "group"],
    decimals = N_DECIMALS
)

display(results_table_transfer)

Paired One-Sided Test (Wilcoxon Signed-Rank): n = 45
H₀: Δ EI ≥ 0
H₁: Δ EI < 0
Median Δ EI: Median of paired differences (falsified - original), not the difference of marginal medians
Rank-biserial r: Raw paired effect size; negative values indicate falsified < original
One-sided p: Wilcoxon signed-rank p-value for H₁
Holm-adj. p: Holm-Bonferroni adjusted one-sided p-value
Diff.: Yes if Holm-adj. p < 0.05 and Median Δ < 0
Significance codes reflect Holm-adj. p
*** p < 0.001, ** p < 0.01, * p < 0.05

                              Median Δ EI Rank-biserial r One-sided p  \
Falsification Method
frozen        target remap          -0.02           -0.38       0.013
              random generate       -0.04           -0.91      <0.001
              vector generate       -0.03           -0.74      <0.001
retrain       target remap          -0.09           -0.53      <0.001
              random generate       -0.02           -0.59      <0.001
              vector generate       -0.03           -0.57      <0.001

                              Holm-adj. p Sig. Diff.
Falsification Method
frozen        target remap          0.013    *   Yes
              random generate      <0.001  ***   Yes
              vector generate      <0.001  ***   Yes
retrain       target remap          0.001   **   Yes
              random generate      <0.001  ***   Yes
              vector generate      <0.001  ***   Yes

In [9]:
## median falsified transfer metrics
transfer_summary = stat_falsified_summary(
    results = results_falsified_transfer,
    metrics = FRONTIER_METRICS,
    decimals = 2
)

display(transfer_summary)

                                        EI [IQR]   VR   MV    MS
Falsification Method
original      original         0.76 [0.71, 0.82]  0.0  0.0  5.95
frozen        target remap     0.73 [0.71, 0.78]  0.0  0.0  6.31
              random generate  0.72 [0.67, 0.77]  0.0  0.0  8.89
              vector generate  0.74 [0.68, 0.76]  0.0  0.0  7.43
retrain       target remap     0.71 [0.64, 0.77]  0.0  0.0  6.36
              random generate  0.75 [0.70, 0.77]  0.0  0.0  7.33
              vector generate  0.74 [0.68, 0.76]  0.0  0.0  6.71

_All three falsification types significantly reduced frontier efficiency under both protocols after Holm correction. Frozen falsifications produced median Δ EI of −0.02 for target permutation, −0.04 for random generation, and −0.03 for vector generation (all Holm-adjusted p ≤ 0.013). After retraining, median Δ EI was −0.09 for target permutation, −0.02 for random generation, and −0.03 for vector generation (all Holm-adjusted p ≤ 0.001). Degrading the representation–target correspondence or the feature structure thus consistently impairs frontier efficiency._

## Prediction Consensus Difference Test
The prediction consensus falsifiability test probes whether falsified data produce weaker agreement between frontier predictions and observed capacity ordering than original data. Each falsification method is tested with a paired one-sided Wilcoxon signed-rank statistic comparing falsified and original CI values, with Δ defined as falsified - original.

- **$H_0$**: Falsified CI does not fall below original CI ($\Delta CI \ge 0$).
- **$H_1$**: Falsified CI falls below original CI ($\Delta CI < 0$).

Rejecting $H_0$ establishes that prediction consensus is significantly weaker on falsified data than on original data.

### Falsification Protocol
Each falsification method is treated as an independent destructive intervention on the signal used for consensus. Frozen contrasts evaluate whether original model fits retain consensus when scored on falsified data. Retrained contrasts evaluate whether refitting on falsified data restores consensus with the original-data baseline.

### Empirical Test Specification
Original and falsified CI values are paired on (model $\times$ domain) within each falsification method and protocol. The paired median shift, rank-biserial effect size, and Holm-adjusted one-sided p-value summarize whether each intervention produces a consistent loss of prediction consensus.

In [10]:
## wilcoxon signed-rank test for falsified prediction consensus
results_table_agreement = stat_falsified_test(
    results = results_falsified_agreement,
    feat_value = ["ci"],
    feat_pairs = ["model", "group"],
    decimals = N_DECIMALS
)

display(results_table_agreement)

Paired One-Sided Test (Wilcoxon Signed-Rank): n = 45
H₀: Δ CI ≥ 0
H₁: Δ CI < 0
Median Δ CI: Median of paired differences (falsified - original), not the difference of marginal medians
Rank-biserial r: Raw paired effect size; negative values indicate falsified < original
One-sided p: Wilcoxon signed-rank p-value for H₁
Holm-adj. p: Holm-Bonferroni adjusted one-sided p-value
Diff.: Yes if Holm-adj. p < 0.05 and Median Δ < 0
Significance codes reflect Holm-adj. p
*** p < 0.001, ** p < 0.01, * p < 0.05

                              Median Δ CI Rank-biserial r One-sided p  \
Falsification Method
frozen        target remap          -0.29           -0.97      <0.001
              random generate       -0.28           -0.91      <0.001
              vector generate       -0.21           -0.88      <0.001
retrain       target remap          -0.24           -0.99      <0.001
              random generate       -0.18           -0.93      <0.001
              vector generate       -0.30           -0.97      <0.001

                              Holm-adj. p Sig. Diff.
Falsification Method
frozen        target remap         <0.001  ***   Yes
              random generate      <0.001  ***   Yes
              vector generate      <0.001  ***   Yes
retrain       target remap         <0.001  ***   Yes
              random generate      <0.001  ***   Yes
              vector generate      <0.001  ***   Yes

In [11]:
## median falsified prediction consensus metrics
agreement_summary = stat_falsified_summary(
    results = results_falsified_agreement,
    metrics = CONSENSUS_METRICS,
    decimals = N_DECIMALS
)

display(agreement_summary)

                                        CI [IQR]    ρ   RBO   DCR
Falsification Method
original      original         0.84 [0.77, 0.92]  0.6  0.86  0.78
frozen        target remap     0.53 [0.49, 0.63] -0.3  0.78  0.59
              random generate  0.52 [0.43, 0.67] -0.3  0.78  0.63
              vector generate  0.65 [0.55, 0.69]  0.1  0.83  0.57
retrain       target remap     0.58 [0.48, 0.61] -0.3  0.78  0.65
              random generate  0.63 [0.55, 0.71]  0.0  0.81  0.61
              vector generate  0.54 [0.47, 0.60] -0.3  0.78  0.61

_Every falsification type significantly reduced prediction consensus under both protocols after Holm correction. Median Δ CI ranged from −0.29 to −0.21 under the frozen protocol and from −0.30 to −0.18 after retraining, with rank-biserial effects from −0.88 to −0.99 (all Holm-adjusted p < 0.001). Retraining therefore did not restore prediction consensus for any falsification type._

## Pairwise Prediction Consensus Evaluation
The pairwise prediction consensus evaluation probes whether falsified inputs preserve agreement among independently trained frontiers. Unlike the transfer and prediction-consensus sections, this is a descriptive stability analysis rather than a formal falsifiability test. Agreement is computed across all model pairs using the same consensus metrics.

- **Spearman (`ρ`)**: Global rank agreement between paired model frontiers.
- **Rank-Biased Overlap (`RBO`)**: Top-weighted agreement, emphasizing the high-capacity tail.
- **Distance Correlation (`dCor`)**: Nonlinear dependence between paired model frontiers.
- **Consensus Index (`CI`)**: Geometric mean of agreement-scaled `ρ`, `RBO`, and `dCor`.

### Falsification Protocol
The evaluation is restricted to the frozen protocol, so model fits remain anchored to the original empirical manifold while falsified inputs are scored. Only falsified-input rows enter the preview and visualization; the original baseline remains available in the compiled results for comparison.

### Reporting Convention
Each falsification method contributes one value per model pair under the frozen protocol. The preview reports medians across all retained frozen falsified pairwise comparisons. Prior to compounding, `ρ` is rescaled from `[-1, 1]` to `[0, 1]` so that negative rank agreement lowers `CI` without collapsing to a single floor. Higher values indicate stronger falsification-stable pairwise prediction consensus.

In [12]:
## consensus preview
results_falsified_consensus_fals = results_falsified_consensus.loc[
    (results_falsified_consensus["Falsification"] == "frozen")
    & (results_falsified_consensus["condition"] == "falsified")
].copy()

round(number = results_falsified_consensus_fals[CONSENSUS_METRICS].median(), ndigits = N_DECIMALS)

rho    0.64
rbo    0.66
dcr    0.67
ci     0.70
dtype: float64

_Frozen falsification reduces pairwise prediction consensus for generated-input interventions, with median `CI` = 0.70 across retained pairwise comparisons. Target remap preserves frozen consensus by construction because input features are unchanged, whereas random and vector generation visibly weaken agreement among fitted frontiers. Pairwise prediction consensus therefore depends on coherent event-network geometry rather than arbitrary or generated input structure._

## Summary

In [13]:
## manuscript master table for falsification validity
display_table = main_table(
    results_left = results_table_transfer.reset_index(),
    results_right = results_table_agreement.reset_index(),
    index_feat = ["Falsification", "Method"],
    value_feat_left = ["Median Δ EI", "Rank-biserial r", "Sig.", "Diff."],
    value_feat_right = ["Median Δ CI", "Rank-biserial r", "Sig.", "Diff."],
    header_left = "Domain Transfer",
    header_right = "Estimation-Observation Consensus",
    short_feat_left = ["Δ EI", "r", "Sig.", "Diff."],
    short_feat_right = ["Δ CI", "r", "Sig.", "Diff."],
    row_order = [
        ("frozen",  "target remap"), ("frozen",  "random generate"), ("frozen",  "vector generate"),
        ("retrain", "target remap"), ("retrain", "random generate"), ("retrain", "vector generate"),
    ],
)

display(display_table)
display(
    Markdown(
    "**Δ EI**, **Δ CI**: median signed difference between falsified and original performance, where negative values indicate falsified data underperform original data. "
    "**r**: rank-biserial correlation effect size, where negative values favor original > falsified. "
    "**Sig.**: Holm-adjusted one-sided Wilcoxon *p* below threshold to test within each outcome "
    "(\*\*\* *p* < 0.001, \*\* *p* < 0.01, \* *p* < 0.05); significance supports the difference hypothesis "
    "H₁: Δ < 0, that falsified data underperform original data. "
    "**Diff.**: difference supported when Holm-adjusted *p* < 0.05 and median Δ < 0. "
    "Each test is conducted on *n* = 45 (9 models × 5 domains)."
    )
)

                              Domain Transfer                    \
                                         Δ EI      r Sig. Diff.
Falsification Method
frozen        target remap              -0.02  -0.38    *   Yes
              random generate           -0.04  -0.91  ***   Yes
              vector generate           -0.03  -0.74  ***   Yes
retrain       target remap              -0.09  -0.53   **   Yes
              random generate           -0.02  -0.59  ***   Yes
              vector generate           -0.03  -0.57  ***   Yes

                              Estimation-Observation Consensus              \
                                                          Δ CI      r Sig.
Falsification Method
frozen        target remap                               -0.29  -0.97  ***
              random generate                            -0.28  -0.91  ***
              vector generate                            -0.21  -0.88  ***
retrain       target remap                               -0.24  -0.99  ***
              random generate                            -0.18  -0.93  ***
              vector generate                            -0.30  -0.97  ***


                              Diff.
Falsification Method
frozen        target remap      Yes
              random generate   Yes
              vector generate   Yes
retrain       target remap      Yes
              random generate   Yes
              vector generate   Yes

**Δ EI**, **Δ CI**: median signed difference between falsified and original performance, where negative values indicate falsified data underperform original data. **r**: rank-biserial correlation effect size, where negative values favor original > falsified. **Sig.**: Holm-adjusted one-sided Wilcoxon *p* below threshold to test within each outcome (\*\*\* *p* < 0.001, \*\* *p* < 0.01, \* *p* < 0.05); significance supports the difference hypothesis H₁: Δ < 0, that falsified data underperform original data. **Diff.**: difference supported when Holm-adjusted *p* < 0.05 and median Δ < 0. Each test is conducted on *n* = 45 (9 models × 5 domains).